version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ruby"
    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - 'yarp'
