name: Update gem RBIs on Dependabot PRs
on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot_update_rbis:
    uses: andyw8/ruby-lsp/.github/workflows/dependabot_update_rbis.yml@main
