name: CI (indexing)

on:
  push:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'
  pull_request:
    paths:
      - 'Gemfile.lock'
      - 'lib/ruby_indexer/**'

jobs:
  indexing_sanity_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          bundler-cache: true

      - name: Index Top 100 Ruby gems
        run: bundle exec rake index:topgems
